apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: kacp
    app.kubernetes.io/name: kacp
  name: kacp
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kacp
      app.kubernetes.io/name: kacp
  template:
    metadata:
      labels:
        app: kacp
        app.kubernetes.io/name: kacp
    spec:
      containers:
      - name: kacp
        image: docker.io/sebt3/kacp:0.5.0
        imagePullPolicy: IfNotPresent
        env:
        - name: CONTROLLER_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TARGET_FILE
          value: "/etc/kubernetes/config/AuthenticationConfiguration.yaml"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/kubernetes/config
          name: auth-cfg
        - mountPath: /etc/kacp/kacp.yaml
          name: config
          subPath: kacp.yaml
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      restartPolicy: Always
      serviceAccount: kacp
      serviceAccountName: kacp
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsNonRoot: true
        runAsUser: 0
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /etc/kubernetes/config
          type: ""
        name: auth-cfg
      - name: config
        configMap:
          defaultMode: 292
          items:
          - key: kacp.yaml
            path: kacp.yaml
          name: kacp-config
