---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kacp
  labels:
    app: kacp
    app.kubernetes.io/name: kacp
  namespace: default
automountServiceAccountToken: true
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kacp-controller
rules:
  - apiGroups: ["kacp.solidite.fr"]
    resources: ["kubeauthenticationconfigurations", "kubeauthenticationconfigurations/status", "kubeauthenticationconfigurations/finalizers"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kacp-controller
subjects:
- kind: ServiceAccount
  namespace: default
  name: kacp
roleRef:
  kind: ClusterRole
  name: kacp-controller
  apiGroup: rbac.authorization.k8s.io
