name: ci

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup qemu for multi-arch support
      - name: Docker Setup qemu-action
        uses: docker/setup-qemu-action@v2
      # Build and push with docker buildx
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure tags based on git tags + latest
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ github.repository_owner }}/kacp
          tags: |
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Docker login on main origin
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker buildx
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha,scope=base
          cache-to: type=gha,scope=base,mode=max
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
